<?php
/**
 * @file A module which provides funcionallity for add_on products.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function wlw_addon_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {

    case 'help.page.wlw_addon':
      $output = '';
      $output .= '<h3>' . t('Functionality') . '</h3>';
      $output .= '<ol>';
      $output .= '<li>' . t('Provides FieldFormatter with a addToCartForm for multible products with checkboxes.') . '</li>';
      $output .= '<li>' . t('Calculates the price of the checked product variations with jQuery in the product display.') . '</li>';
      $output .= '</ol>';
      $output .= '<h3>' . t('Configuration') . '</h3>';
      $output .= '<ol>';
      $output .= '<li>' . t('Configure the FieldFormatter "WLW Multible Product add to cart form" to product-type (Add-on) in <a href="/admin/commerce/config/product-types/add_on/edit/display" target="_blank">manage display</a> to the Variation Field.') . '</li>';
      $output .= '</ol>';
      return $output;
  }
}
