<?php
/**
 * @file: A module which profides functioallity for course products.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function wlw_course_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {

    case 'help.page.wlw_course':
      $output = '';
      $output .= '<h3>' . t('Provided Functionality') . '</h3>';
      $output .= '<ol>';
      $output .= '<li>' . t('Provides FieldFormatter "WLW Course Link"') . '</li>';
      $output .= '<li>' . t('Provides FieldFormatter with a addToCartForm.') . '</li>';
      $output .= '</ol>';
      $output .= '<h3>' . t('Dependent Configuration') . '</h3>';
      $output .= '<ol>';
      $output .= '<li>' . t('Node Type "course" needs to have a "entity_reverence" field for products with name "field_product"');
      $output .= '<li>' . t('Configure the FieldFormatter "WLW Course add to cart form" to product-type (course) in <a href="/admin/commerce/config/product-types/course/edit/display" target="_blank">manage display</a> to the Variation Field.') . '</li>';
      $output .= '</ol>';
      return $output;
  }
}

/**
 * Implements hook_theme().
 */
function wlw_course_theme() {
  return [
    'wlw_course_add_to_cart_form' => [
      'render element' => 'course_add_to_cart_form',
    ],
  ];
}

