<?php
/**
 * @file Module file from wlw_cart module.
 */

use Drupal\commerce_order\Entity\OrderInterface;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_views_pre_render().
 */
function wlw_cart_views_pre_render(ViewExecutable $view) {
  // Adds js library to commerce_cart_form view on /cart page.
  if (isset($view) && ($view->storage->id() == 'commerce_cart_form')) {
    $view->element['#attached']['library'][] = 'wlw_cart/cart-view-js';
  }
}

/**
 * Implements template_preprocess_views_view().
 */
function wlw_theme_preprocess_views_view__commerce_cart_form(&$variables) {

  $order_type_title = '';
  $view = $variables['view'];

  // Gets only first row because the order entity is always the same.
  if ($view->result) {

    $view_result = $view->result[0];
    $order = $view_result->_entity;

    if ($order instanceof OrderInterface) {

      $order_type = $order->get('type')->getValue()[0]['target_id'];

      // Creates views title for each cart on /cart page.
      if ($order_type == 'default') {
        $order_type_title = 'Produkt Bestellung';
      } elseif ($order_type == 'course') {
        $order_type_title = 'Kursbuchung';
      }
      $variables['header'] = t($order_type_title);
    }
  }
}
