<?php
/**
 * @file: A module which provides a interface to optiback.
 *
 * For module global settings
 * @see optiback/OptibackInterface;
 *
 * E-Mail: obtiback@wp11130752.server-he.de
 */

/**
 * Implements hook_theme().
 */
function optiback_theme($existing, $type, $theme, $path) {
  return [
    'optiback_email_wrapper' => [
      'variables' => [
        'message' => NULL,
      ],
    ],
  ];
}


/**
 * Implements hook_mail().
 *
 * Implementation is needed to get it to mailsystem ui.
 */
function optiback_mail($key, &$message, $params) {

  switch ($key) {
    case 'optiback':

      $message['from'] = $params['from'];
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['body'];
      $message['params']['attachments'] = $params['attachments'];
      break;
  }
}
