<?php

/**
 * @file
 * Functions to support theming in the SASS Starterkit subtheme.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_system_theme_settings_alter() for settings form.
 *
 * Replace Barrio setting options with subtheme ones.
 *
 * Example on how to alter theme settings form
 */
function kp_2025_form_system_theme_settings_alter(&$form, FormStateInterface $form_state) {
  $form['components']['navbar']['bootstrap_barrio_navbar_top_background']['#options'] = [
    'bg-primary' => t('Primary'),
    'bg-secondary' => t('Secondary'),
    'bg-light' => t('Light'),
    'bg-dark' => t('Dark'),
    'bg-white' => t('White'),
    'bg-transparent' => t('Transparent'),
  ];
  $form['components']['navbar']['bootstrap_barrio_navbar_background']['#options'] = [
    'bg-primary' => t('Primary'),
    'bg-secondary' => t('Secondary'),
    'bg-light' => t('Light'),
    'bg-dark' => t('Dark'),
    'bg-white' => t('White'),
    'bg-transparent' => t('Transparent'),
  ];
}


function kp_2025_preprocess_views_view_fields(&$variables) {
  if (
    $variables['view']->id() === 'oeffnungszeiten' &&
    $variables['view']->current_display === 'block_1'
  ) {
    $node = $variables['row']->_entity;

    if ($node && $node->hasField('field_galeriebild')) {
      $variables['gallery_images'] = [];

      foreach ($node->get('field_galeriebild') as $item) {
        $variables['gallery_images'][] = [
          '#theme' => 'responsive_image_formatter',
          '#item' => $item,
          '#item_attributes' => [],
          '#responsive_image_style_id' => 'square_medium_image',
          '#url' => NULL,
        ];
      }
    }
  }
}
