<?php
/**
 * @file: A module which profides mail logging for each order.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function wlw_order_mail_log_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {

    case 'help.page.wlw_order_mail_log':
      $output = '';
      $output .= '<h3>' . t('Provided Functionality') . '</h3>';
      $output .= '<ol>';
      $output .= '<li>' . t('Mail logging for each order.') . '</li>';
      $output .= '<li>' . t('Provides a block which displays the log entries for this order.') . '</li>';
      $output .= '</ol>';
      $output .= '<h3>' . t('Dependent Configuration') . '</h3>';
      $output .= '<ol>';
      $output .= '<li>' . t('Configure the Block in your admin theme at path /admin/commerce/orders/*/reminder-emails. Needs commerce_order Id in path. <strong>You must setup access control in block configuration.</strong>');
      $output .= '</ol>';
      return $output;
  }
}
