<?php
/**
 * @file: A module which provides a interface to optiback.
 */
/**
 * Implements hook_mail().
 *
 * Implementation is needed to get it to mailsystem ui.
 */
function optiback_export_mail($key, &$message, $params) {

  switch ($key) {
    case 'optiback_export':

      $message['from'] = $params['from'];
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['body'];
      $message['params']['attachments'] = $params['attachments'];
      break;
  }
}
