<?php

/**
 * @file A module which provide extra funcionallity for commerce_promotions.
 */

/**
 * Implements hook_form_FORM_ID_alter().
 * FormId: commerce_checkout_flow_multistep_default
 */
function custom_promotion_form_commerce_checkout_flow_multistep_default_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {

  if($form['#step_id'] === 'order_information') {

    $input = $form_state->getUserInput();
    $coupon_code = trim($input['sidebar']['coupon_redemption']['form']['code']);

    if ($coupon_code) {

      $entity_type_manager = \Drupal::service('entity_type.manager');

      $promotions = $entity_type_manager->getStorage('commerce_promotion')->loadMultiple();

      foreach ($promotions as $promotion) {

        $coupons = $promotion->getCoupons();

        foreach ($coupons as $coupon) {

          if ($coupon_code == $coupon->getCode()) {

            $promotion_name = $promotion->get('display_name')
              ->getValue()[0]['value'];
            $promotion_desc = $promotion->get('description')
              ->getValue()[0]['value'];

            if ($promotion_name) {
              // Creates a info container on top of coupon redemption inline form.
              $form['sidebar']['coupon_redemption']['form']['promotion_info'] = [
                '#type' => 'inline_template',
                '#template' => '<div class="promotion-info"><h2>' . $promotion_name . '</h2><div class="promotion-info-desc">' . $promotion_desc . '</div></div>',
                '#weight' => -1,
              ];
            }
          }
        }
      }
    }
  }
}
