<?php
/**
 * @file
 * Provides custom functionality for Commerce Promotions.
 */

/**
 * Implements hook_commerce_inline_form_info_alter().
 */
function custom_promotion_commerce_inline_form_info_alter(array &$definitions) {
  if (isset($definitions['coupon_redemption'])) {
    $definitions['coupon_redemption']['class'] =
      \Drupal\custom_promotion\Plugin\Commerce\InlineForm\CustomCouponRedemption::class;
  }
}

